stages:
  - build

build-job:
  stage: build
  tags: 
    - shell
  script:
    - log() { echo -e "\e[30;47m ${1} \e[0m ${@:2}"; } # $1 background white
    - log CI_JOB_STAGE ${CI_JOB_STAGE}
    - log CI_COMMIT_BRANCH ${CI_COMMIT_BRANCH}
    - log CI_COMMIT_SHA ${CI_COMMIT_SHA}
    - log REGISTRY_URL ${REGISTRY_URL}
    - log REPOSITORY_NAME ${REPOSITORY_NAME}
    - log REGISTRY_LOGIN ${REGISTRY_LOGIN}
    - log REGISTRY_PASSWORD ${REGISTRY_PASSWORD}
    - cd vote
    - TAG_SHA=${REGISTRY_URL}/${REPOSITORY_NAME}:${CI_COMMIT_SHA}
    - log TAG_SHA ${TAG_SHA}
    - docker image build --tag ${TAG_SHA} .
    - docker login --username ${REGISTRY_LOGIN} --password ${REGISTRY_PASSWORD} ${REGISTRY_URL}
    - docker push ${TAG_SHA}
